spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raynkan/spring-clound/tree/master/config-repo-demo
server:
  port: 1201